-- 004_add_reports_tables.sql — NEUTRALISÉE (voir migration 029 + 039).
--
-- Historique : cette migration créait une table `reports` legacy (pdf_url,
-- pdf_path, recipient_email, data_snapshot) + une table `report_data` jamais
-- utilisée par le code. La migration 029 (schéma actuel : title, kind,
-- html_content…) faisait CREATE TABLE IF NOT EXISTS : sur une base fraîche
-- appliquant 001→038 dans l'ordre, le schéma legacy gagnait et cassait à la
-- fois le service de génération (colonne title absente) et la migration 033
-- (index trigramme sur reports.title).
--
-- La prod est au schéma 029. Cette migration est donc neutralisée pour que
-- les bases fraîches (CI, dev, restauration) construisent directement le bon
-- schéma via 029. Le nettoyage de `report_data` sur les bases existantes est
-- fait par la migration 039.
SELECT 1;
